[tool.pytest.ini_options]
generate_report_on_test = true
log_cli = true
log_cli_level = "warn"
markers = [
    "audio: test is reliant on audio",
    "pynput: test uses pynput package",
    "incident: incident smoke tests",
    "unstable: temporary mark for unstable tests"
]
testpaths = [
    "tests"
]
addopts = "-vs -m 'not incident' -m 'not unstable' --ci --html=/builds/worker/artifacts/report.html"

[tool.ruff]
target-version = "py310"
