[tool.pytest.ini_options]
generate_report_on_test = true
addopts = "-vs --html=/builds/worker/artifacts/report.html"
markers = [
    "pynput: test uses pynput package"
]

[tool.ruff]
target-version = "py310"
