name: Debug macOS Runner

on: [push]

jobs:
  debug:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install SSH server
        run: |
          sudo systemsetup -f -setremotelogin on
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY }}" >> ~/.ssh/authorized_keys
          sudo chmod 600 ~/.ssh/authorized_keys
          sudo chown $(whoami) ~/.ssh/authorized_keys
          sudo launchctl list | grep xsan
          sudo launchctl start com.openssh.sshd

      - name: Output SSH Command
        run: echo "ssh -i <path-to-private-key> -o 'StrictHostKeyChecking=no' runner@$(hostname)"

      - name: Keep Job Running
        run: |
          while true; do sleep 100; done