---
name: Mac and Windows Smoke

run-name: ${{ github.actor }} is running smoke tests
on:
  pull_request:
  push:

jobs:
  Smoke-Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          mkdir -p artifacts;
          pip3 install 'pipenv==2023.11.15';
          pip3 install 'ruff>=0.4.8,<0.5';
          bash collect_executables.sh;
          rm ./pyproject.toml;
          mv ./ci_pyproject.toml ./pyproject.toml;
          pipenv install;
      - name: Run Smoke Tests in Win
        run: |
          pipenv run pytest --fx-executable ./firefox/firefox tests/address_bar_and_search/test_search_bar_result.py
          mv artifacts artifacts-win
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-win
          path: artifacts-win
  Smoke-MacOS:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          mkdir -p artifacts;
          pip3 install 'pipenv==2023.11.15';
          pip3 install 'ruff>=0.4.8,<0.5';
          bash collect_executables.sh;
          rm ./pyproject.toml;
          mv ./ci_pyproject.toml ./pyproject.toml;
          pipenv install;
      - name: Run Smoke Tests in MacOS
        run: |
          pipenv run pytest --fx-executable ./firefox/firefox tests/address_bar_and_search/test_search_bar_result.py
          mv artifacts artifacts-mac
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-mac
          path: artifacts-mac

  Use-Artifacts:
    runs-on: ubuntu-latest
    needs:
      - Smoke-Windows
      - Smoke-MacOS
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: artifacts-win
          path: artifacts-win
      - name: Download MacOS artifact
        uses: actions/download-artifact@v4
        with:
          name: artifacts-mac
          path: artifacts-mac
      - name: List downloaded files
        run: ls artifacts-win/
      - name: List downloaded MacOS files
        run: ls artifacts-mac/
      - name: Run script with secret
        env:
          MY_SECRET_TOKEN: ${{ secrets.SLACK_KEY }}
        run: |
          python notifier.py

      # - name: Use artifact
      #   run: |
      #     # Add your commands here to use the downloaded artifacts
      #     cat downloaded-artifacts/artifacts-win/some-file.txt